baseURL = 'https://jimmychin946.github.io/profile'
# baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-profile'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
